# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213cede195785a4f0ad5888a3cc54ac228a639b9528ac7db59580b2ee76f8f179ec1ff221ae080f1779da0a1fb9ac9794c7d0283253275795aa58c4c99d2101d

test:
  secret_key_base: fe2786fc585269d227a427b9bf4a29ba09d847594582e8b720af4d44aa2a064eb00b8ebc7acfc3a0d195c5009d1cb8dcfd07a9c8b97ad00bf9de2a99f8b79f86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
