module.exports = {
  ADD_CLASS: "ADD_CLASS",
  UPDATE_CLASS: "UPDATE_CLASS",
  REMOVE_CLASS: "REMOVE_CLASS",
  ADD_SECTION: "ADD_SECTION",
  UPDATE_SECTION: "UPDATE_SECTION",
  REMOVE_SECTION: "REMOVE_SECTION"
};
